// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ROFZZ-dfWyDrszGdDsIin8m43fBdrKo',
    appId: '1:385091224716:web:2220ccc07138844f4267a9',
    messagingSenderId: '385091224716',
    projectId: 'blackcabin',
    authDomain: 'blackcabin.firebaseapp.com',
    storageBucket: 'blackcabin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAFncZ9hykK2sKxYuirmI9neyuHSKSJRQ',
    appId: '1:385091224716:android:9863b141f62e85254267a9',
    messagingSenderId: '385091224716',
    projectId: 'blackcabin',
    storageBucket: 'blackcabin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASOxBtgMDSvNt502pe2STBD8X9ntaSd1s',
    appId: '1:385091224716:ios:55beb44290dfbd564267a9',
    messagingSenderId: '385091224716',
    projectId: 'blackcabin',
    storageBucket: 'blackcabin.firebasestorage.app',
    iosBundleId: 'com.example.blackcabin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASOxBtgMDSvNt502pe2STBD8X9ntaSd1s',
    appId: '1:385091224716:ios:55beb44290dfbd564267a9',
    messagingSenderId: '385091224716',
    projectId: 'blackcabin',
    storageBucket: 'blackcabin.firebasestorage.app',
    iosBundleId: 'com.example.blackcabin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ROFZZ-dfWyDrszGdDsIin8m43fBdrKo',
    appId: '1:385091224716:web:1c669cf08032b5094267a9',
    messagingSenderId: '385091224716',
    projectId: 'blackcabin',
    authDomain: 'blackcabin.firebaseapp.com',
    storageBucket: 'blackcabin.firebasestorage.app',
  );
}
